---
- name: Create message of the day
  hosts: all
  become: true
  tasks:
    - name: Edit message of the day file
      ansible.builtin.lineinfile:
        path: /etc/motd
        state: present
        line: 'This is my server on {{ ansible_default_ipv4.address }}'
