---
- name: Create motd Happy Train
  hosts: app
  become: true
  tasks:
    - name: Install epel-release
      ansible.builtin.yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        state: present


    - name: Install happy train (Steam Locomotive)
      ansible.builtin.yum:
        name: sl
        state: present
