---
- name: Install mariadb database
  hosts: db
  become: true
  collections:
    - community.mysql
  tasks:

    - name: Install mariadb-server & python3-PyMySQL
      ansible.builtin.yum:


    - name: Start and enable the mariadb service
      ansible.builtin.service:
      


    - name: Set Mysql root password
      community.mysql.mysql_user:
        login_user: root
        login_password: ""
        name: root
        check_implicit_admin: true
        login_unix_socket: /var/run/mysqld/mysqld.sock
        password: change_me
        host: localhost
