---
- name: Install mariadb database
  hosts: db
  become: true
  tasks:

    - name: Install mariadb-server & python3-PyMySQL
      ansible.builtin.yum:


    - name: Start mariadb
      ansible.builtin.service:
      


    - name: Set Mysql root password
      community.mysql.mysql_user:
        login_user: root
        login_password: password
        user: root
        check_implicit_admin: true
        password: password
        host:
