---
- name: Install mariadb database
  hosts: db
  become: true
  collections:
    - community.mysql
  tasks:
    - name: Install mariadb-server & python3-PyMySQL
      ansible.builtin.yum:
        name:
          - mariadb-server
          - python3-PyMySQL
        state: present


    - name: Start and enable the mariadb service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true

      # This may not working depending on the network
    - name: Set Mysql root password
      community.mysql.mysql_user:
        login_user: root
        login_password: ""
        name: root
        login_unix_socket: /var/run/mysqld/mysqld.sock
        check_implicit_admin: true
        password: password
        host: localhost
      ignore_errors: true
